### ISSUE TITLE
Add Authentication support

### ISSUE THREAD

**Issue by geekpete** [nfsec/eshell#1]
For use with shield or basic proxy fronting ES.

**Comment by nfsec** [comment]
Good Idea.

**Comment by geekpete** [comment]
I often just use "http://$AUTH@whateverserver:9200" as a url after first initialising the $AUTH environment variable beforehand. 

```
#!/bin/bash
export AUTH="mylogin:mypassword"
```

Then `source auth.sh` to load it.

This might be the least amount of work to get auth working at first as you should be able to just pass that whole string as the url. You just need to ensure your app can take that as a valid input for the url.

After that, you could have additional parameters for username/password and maybe the option to prompt for password.

**Comment by nfsec** [comment]
In **0.3.11** HTTP Basic Authentication is supported by the environment variable **$ESAUTH** in the format: **login:password**.
